### ISSUE TITLE
sunn hemp destruction in natural plot

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#13]
Sometime in the last 3 days, something started munching the tops off of the sunn hemp in the natural plot here. 
One plot (150) is almost completely decimated. A few others have moderate or minor damage.
![img_0284](https://user-images.githubusercontent.com/36899811/40840163-8866cb6e-6573-11e8-9395-44c6a6e16849.jpg)
![img_0281](https://user-images.githubusercontent.com/36899811/40840173-942ce136-6573-11e8-8c32-8bb53c37f9a6.jpg)

**Comment by readersm** [comment]
They did some more damage over the weekend... I'll go out and collect some damage data tomorrow. Does percent of plot effected sound good with ranges <25%, 25-50%, 50-75% and more than 75%?

**Comment by Thioro18** [comment]
Oh no! Is it only the Sunn hemp? We will count the number of plant before harvesting the biomass. I think if you have interns who can help you count now that will be great otherwise the percent damage may do.

**Comment by readersm** [comment]
It is only the sunn hemp thankfully. They have chomped some all the way to the ground, so I'm not sure if we could even count accurately. The farm manager assistant said he will be trapping and hunting them.

**Comment by readersm** [comment]
Sad news :(
Plots | Site | Species 1 | % damage
-- | -- | -- | --
145 | SP | SH | >75
147 | SP | SH | >75
150 | SP | SH | 100
151 | SP | SH | 25-50
153 | SP | SH | 50-75
155 | SP | SH | 50-75
158 | SP | SH | 50-75
160 | SP | SH | 50-75
161 | SP | SH | 50-75
164 | SP | SH | 50-75
166 | SP | SH | >75
168 | SP | SH | 25-50
169 | SP | SH | >75
170 | SP | SH | >75
173 | SP | SH | >75
177 | SP | SH | 50-75
178 | SP | SH | 25-50
180 | SP | SH | 50-75

Also, the sorghum and velvet bean are also struggling in the SP plot. I'll attach photos. The leaves look really nutrient deficient and the heights are WAY under (more than half) the heights of the AG plot for the sorghum. I think the soil isn't healthy enough to support growth for the sunn hemp and sorghum. The velvet beans are the only ones that are ok though they look a lot more yellow. I have the first CHL readings now which I will look at tomorrow.
Yellow velvet bean
![yellow velvet bean](https://user-images.githubusercontent.com/36899811/41000026-ae9e761e-68da-11e8-9f1b-c6cc7fa9df77.jpg)
Red stems on sorghum
![red stems sorghum](https://user-images.githubusercontent.com/36899811/41000027-aeb15860-68da-11e8-9780-7a43754030e7.jpg)
Saddest of the sad sorghum plants (still look like they are a week old)
![saddest of the sad sorghum plants](https://user-images.githubusercontent.com/36899811/41000028-aec494c0-68da-11e8-81ab-541818cb5e62.jpg)
burn of crotalaria after rabbit munches growing point...
![burn of crotalaria after rabbit munches growing point](https://user-images.githubusercontent.com/36899811/41000029-aed9c8cc-68da-11e8-847e-0bb33b616987.jpg)

**Comment by brymz** [comment]
Sad news... and/or very interesting. We have a lot to learn! I am confident we'll have plenty of useful data for your project.

**Comment by Thioro18** [comment]
What were the main tree species in the SP?

**Comment by readersm** [comment]
Mostly screw pines (_Pandanus amaryllifolius_) and a lot of saw palmetto (_Serenoa repens_). I don't know if either of them have alleopathic properties, but they might! I'll do a little literature digging.

**Comment by Thioro18** [comment]
I will run the soil sample analysis for pH because pine needles are acid. I am not sure about the allelopathy but I bet the acidity might be one of the reasons.

**Comment by Thioro18** [comment]
Hi Stacy,

If you want to add that high pH organic amendment, there are few things you need to consider:
1- how much increase in soil pH do you need for the cover crop to grow
2- Buffer capacity of the soil (Each soil type has its buffering capacity which is the degree change in pH given the added amendment). 
3- Which soil volume or depth you want the pH to increase
4- The chemical composition of the amendment and its fineness
Since this seems to be a long process, I would recommend to do some pot tests where add different rates of the amendment and see how much increase you have in your soil pH.

**Comment by brymz** [comment]
I think container trials would be a GREAT next step.
