### ISSUE TITLE
Individual tasks (ECHO)

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#17]
- [x] organize datasheets for data analysis  (verify same as Thioro's) and upload to GitHub using R.
- [x] input season 2 biomass data and upload to GitHub
- [x] finalize committee
- [x] work on data carpentry workshop
- [x] spring evaluation
- [x] discuss what to do in SP plot (low pH)
- [x] update methods section
- [x] put program of study up on my repository
- [x] put up page on labwiki about Agroecology Master's program (resources and considerations)
- [x] write up student spotlight for Romain and give to him
- [x] change last name in UF system

**Comment by brymz** [comment]
Yep. This would be a great example of multiple issues.

FYI, you can reference an existing issue as #1.

**Comment by brymz** [comment]
Hey @readersm, I think we completed these tasks. You can close the issue if you agree.
