### ISSUE TITLE
Data Organization

### ISSUE THREAD

**Issue by Thioro18** [TREC-Agroecology/agroecosystems#20]
Under this address: T:\Agronomy\CropDiversity\AgroecosystemsExperiment/1_RawData

- [x] File name (rSoilAnalysis_TREC_ECHO) has Soil OM, Total P, soil BD, soil NO3 and NH4 (complete)

- [ ] File name (rGHG_TREC_20181213): raw data sent by Dr. Smyth. The units are in ppmv and need to be converted into mg/m2/h. This was done in the excel file named "aGHG_TREC_20181213" located in the folder 2_DataAnalysis
- [x] File name (rHarvest1_092018_TREC)
- [x] File name (rHarvest2_01142019_TREC)
- [x] File name (rHDC_May-July_2018)
- [x] File name (rHDC_Nov2018-Jan2019)
- [x] File name (rPDS_ECHO-2018)
- [x] File name (rPDS_TREC-2018)
- [x] File name (rPDS-PlotCoordinates-TREC) 
- [x] File name (rSoilAnalysis_TREC_ECHO)
- [ ] File name (SiteINFO)

Under this address: T:\Agronomy\CropDiversity\AgroecosystemsExperiment/2_DataAnalysis

- [ ] File name (aWSD-May-Nov2018 _FinalVersion) has weather station data from May to November 2018 and are re-organized in order as: 
- Rain, mm (LGR S/N: 20346239, SEN S/N: 20354813)
- PAR, uE (LGR S/N: 20346239, SEN S/N: 20338885)
- Temp, øC (LGR S/N: 20346239, SEN S/N: 20355489)
- RH, % (LGR S/N: 20346239, SEN S/N: 20355489)
- Water Content, m?/m? (LGR S/N: 20346239, SEN S/N: 20367681)
- Water Content, m?/m? (LGR S/N: 20346239, SEN S/N: 20367685)
- Wind Speed, m/s (LGR S/N: 20346239, SEN S/N: 20335985)
- Wind Direction, ? (LGR S/N: 20346239, SEN S/N: 20346987)
- Gust Speed, m/s (LGR S/N: 20346239, SEN S/N: 20335985)

- [ ]

**Comment by brymz** [comment]
> rHDC_May-July_2018

- Only chlorophyll week 4?
- Combine data into single table

**Comment by brymz** [comment]
Please, confirm location (binder?) of all hard copy data.

**Comment by brymz** [comment]
> rHDC_Nov2018-Jan2019

- Clarify methods for height... How do you determine "small canopy, tall canopy, and average canopy"?

**Comment by brymz** [comment]
> rSoilAnalysis_TREC_ECHO

Why might the `SOM%` for the `FO` be higher than the `VF`?

**Comment by Thioro18** [comment]
> > rSoilAnalysis_TREC_ECHO
> 
> Why might the `SOM%` for the `FO` be higher than the `VF`?

I am not sure exactly why but both the VF and FO had cover crops before we set up our experiment. In the VF, half of the plot experiment is in the post-cover crop area whereas in the FO the entire plot experiment is the post CC area.

**Comment by Thioro18** [comment]
> > rHDC_Nov2018-Jan2019
> 
> * Clarify methods for height... How do you determine "small canopy, tall canopy, and average canopy"?

After 4 weeks, the canopy within each subplot has at least 2 strata. So, based on visual observation, you can determine the different canopy heights

**Comment by Thioro18** [comment]
> Please, confirm location (binder?) of all hard copy data.

All of the original datasheet are scanned and save in the folder name Scanned spreadsheet in the shared drive under "AgroecosystemsExperiment/3_FieldSpreadsheet-ExpDesign/ScannedDataSheet"

**Comment by Thioro18** [comment]
> > rHDC_May-July_2018
> 
> * Only chlorophyll week 4?
> * Missing height data for HH row 6
> * Will ask @Danielcalza to combine data into single table

Yes, we only have 1 chlorophyll sampling event and no diameter.

**Comment by brymz** [comment]
@Thioro18,

Do the 216 `SAMPLE ID` correspond with `PlotID` for the `NO3-N` and `NH4-N` samples?

**Comment by Thioro18** [comment]
> @Thioro18,
> 
> Do the 216 `SAMPLE ID` correspond with `PlotID` for the `NO3-N` and `NH4-N` samples?

Yes! SampleID is the same as PlotID.

**Comment by brymz** [comment]
@Danielcalza,

Please, add missing data to `rHDC_May-June2018.xlsx` for `SamplingWeek = 4`, `Location = HH` and `Row = 6`.

**Comment by Danielcalza** [comment]
Okay, the data has been added to a new file rHDC_May-June2018_n
