### ISSUE TITLE
Planning and preparation of cover crops [April-July]

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/agroecosystems#21]
April
.
Week of 4/01 - 4/05 – Check and confirm supplies (seeds, measuring spoons, flags, soil sampling bags, bulk density) and begin communication with field crew for scheduling.
WO 4/08 - 4/12 –Seeds weighed and set in bags accordingly, and all other materials ready, confirm field crew schedule. – Before plots are mowed, take bulk density and remove soil moisture probes, take pictures of plots before and after mowing.  
WO 4/08 - 4/12 – Plots plowed once probes removed, wait two weeks after plowing to allow the plant matter to breakdown before disking. 
WO 4/15 or 22 – Disking
WO 4/22-26 – Second disking [optional]. 
WO 4/29 – 5/10 – soil sampling. 
.
May
.
5/02 - Bulk density sampling. (VF, HH).
WO 5/06 - SOM samples (All sites),  testing rain and SMP sensors. If plots are raked set up flags. 
WO 5/13 - planting, and place SMP in ground, ready all sampling sheets. 
5/17 - 5/24 - Week 1 and 2 - Emergence recorded. 
WO 5/20 - set up paper bags for biomass sampling. 
.
June
.
WO 6/10 - Week 4 sampling - height, chlorophyll 
6/11 - Collect Weather Station Data 
WO 6/24 - Week 6 sampling - height, chlorophyll 
.
July
.
WO 7/08 - Week 8 sampling - height, chlorophyll.
7/09 - Collect Weather Station Data 
7/10 & 11 - Biomass harvest, and termination

**Comment by Thioro18** [comment]
**Seeding rates for the cover crops**
**SH** (30 lbs/ac) = 33.67 Kg/ha = 3.37 g/m2 = 30.30 g for 9m2 
**SS** (30 lbs/ac) = 33.67 Kg/ha = 3.37 g/m2 = 30.30 g for 9m2 
**VB** (50 lbs/ac) = 56.12 Kg/ha = 5.61 g/m2 = 50.51 g for 9m2 (50 seeds)

**Plot and subplot dimensions**
Plot size = 20m*20m = 65.6ft *65.6ft
Subplot size = 3m*3m = 9.8ft*9.8ft
Space between subplots = 0.43 m = 1.4 ft between subplots
Put a flag at the following measurements:

- 3 m = 9.8 ft
- 3.4 m = 11.2 ft
- 6.4 m = 20.9 ft
- 6.8 m = 22.3 ft
- 9.8 m = 32.1 ft
- 10.2 m = 33.5 ft
- 13.2 m = 43.5 ft
- 13.6 m = 44.7 ft
- 16.6 m = 54.4 ft
- 17.0 m = 55.9 ft
- 20.0 m = 65.6 ft

**Comment by Danielcalza** [comment]
@readersm Hi Stacy! I have prepared the seeds and soil sample bags for ECHO and was curious if there was anything else you needed, and by when you would like to receive everything?

**Comment by readersm** [comment]
Hey Daniel! 
I hope your presentation went well yesterday. 
Thank you so much for prepping. I have measuring cups, plenty of flags and everything else we need!
It would be great to get everything by the week of April 22nd.
My address here is:
17391 Durrance Road
North Fort Myers, FL 33917

**Comment by Danielcalza** [comment]
Thank you! 
Yes it did, and the middle school students asked excellent questions. I'm glad to hear you have everything else. So in that case, I'll be sending everything off next week then. 
I hope you have a great weekend.

**Comment by Danielcalza** [comment]
Hi Stacy, @readersm 
Will you be needing brown paper bags for the biomass samples? 
I am putting the ones for TREC together soon, so let me know and I can get them going for ECHO as well.

**Comment by readersm** [comment]
Nope! We have a bunch. Thanks so much for asking though
> Hi Stacy, @readersm
> Will you be needing brown paper bags for the biomass samples?
> I am putting the ones for TREC together soon, so let me know and I can get them going for ECHO as well.
