### ISSUE TITLE
Supplies for CC experiment

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/agroecosystems#22]
Summer 2019 
- ​216 envelopes for seeds - Coin Envelopes - Kraft, 2 1⁄2 x 4 1⁄4".

- 216 bags for soil samples - Ziploc 1 quart bags.

- 200 flags for marking plots - Uline Orange and blue stake flags. 

- ​Sticker labels for soil sample bags - 1 pack of 25 sheets (30 labels per sheet, 750 labels total) Standard White - 2.625" x 1" Address Labels

- First aid kit

**Comment by brymz** [comment]
Was 200 flags what you need in addition to the 200 we already have? Or are we all set?

**Comment by Danielcalza** [comment]
Cancel the flags. We have plenty and could reuse most of the ones in the plots.
