### ISSUE TITLE
Soil sampling protocol update

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/agroecosystems#25]
- Taken before planting, 2-3 weeks after plowing and disking. 
- Ensure ziplock bags are labeled accordingly. 
- Set up the sampling area, marked out for each sub-plot.  
- Take composite samples, randomly sampled 03 hand-trowels (depth of 10 cm) full of soil per subplot. 
- Sieve samples at 2mm in the field, discard gravel.

**Comment by Danielcalza** [comment]
Please feel free to make any corrections or suggestions. 
I looked back at the other issues and current protocol but would just like some clarifications.

**Comment by readersm** [comment]
Timing looks good, are you just putting out the flags for the sampling area before taking them? If you put anything in-field, you will just have to take it out to disc. 
My only thought of discussion is it may be better to take 10 soil cores per subplot instead of composites with a trowel?

**Comment by brymz** [comment]
It was interesting feedback from your committee to recommend soil cores. I think that makes sense for anywhere but South Florida. There is way too much gravel at TREC for a soil core. The important point I took away was that it should be explicit in our protocol that we get a core-like sample that gathers soil equally across the depth profile. As far as the sample size (n) goes, we're ultimately collecting 36 samples for one (spatially-explicit) plot. We can describe the numerical and spatial differences of the samples, but should not use them for statistical differences among treatment.

@readersm, another important point here is the distinction that TREC has four sites (agroecosystems), while we're looking at ECHO as two, or maybe one. That's right... you're entire experiment might be distilled down to a sample size of n=1. This will make lots of people uncomfortable AND you don't have a control. We should be clear about how this affects the effort/outcome/justification. You need to be confident about your decision.

**Comment by Danielcalza** [comment]
> Timing looks good, are you just putting out the flags for the sampling area before taking them? If you put anything in-field, you will just have to take it out to disc.

Thank you all for you the input and feedback. 

I am planning on only flagging two sides (I tested this method when I did bulk density and it worked great) and using a moving rope system to ensure we are in the correct row and collum of each subplot for sampling. Then I'll remove the flags to disk and mark the rows for planting.

**Comment by Danielcalza** [comment]
Agroecosystems Methods have been updated.
