### ISSUE TITLE
Plant sampling protocol update

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/agroecosystems#26]
- Emergence
	- record at 50% per species per subplot rather than entire plot
	- recorded once

- Chlorophyll
	- use SPAD meter, 03 random samples taken on most basal fully grown leaf of separate individuals for each species per subplot. 
	- record average of 03 measurements
	- biweekly, starting at week 4 (weeks 4, 6, and 8)

- Height of population
	- small canopy, tall canopy, and average canopy for each species per subplot unit
	- biweekly, starting at week 4 (weeks 4, 6, and 8)
	- use meter stick, from ground level

- Stand count
 	- Taken at the time of harvest
	- count number of plant for each species in the 1 m quadrants.
	- use click counter (best) or by hand

**Comment by Danielcalza** [comment]
Please feel free to make any corrections or suggestions.
I reviewed the other issues and current protocol but would just like some clarifications.

**Comment by Thioro18** [comment]
> * Emergence
>   
>   * record at 50% per species per subplot rather than entire plot
>   * recorded once
> * Chlorophyll
>   
>   * 03 random samples taken on mast basal (**what do you mean here?**) fully grown leaf of separate individuals for each species per subplot. **You need to follow the same method as height measurement (small, average, and tall canopies). The SPAD meter will give you the average of 3 measurements. For example, one 1 leaf, you need to place the SPAD at 3 different areas on the leaf then record the average given but the SPAD meter**
>   * biweekly, starting at week 4 (weeks 4, 6, and 8)
> * Height of population
>   
>   * small canopy, tall canopy, and average canopy for each species per subplot unit
>   * biweekly, starting at week 4 (weeks 4, 6, and 8)
>   * use meter stick, from ground level
> * Stand count
>   
>   * count number of plant for each species per subplot unit at harvest. **You only need plant count of the harvested biomass in the 1 m quadrants.** 
>   * **At Harvest**
>   * use click counter (best) or by hand

**Comment by readersm** [comment]
- I  think **mast** is just a typo of **most** (the most basal, fully expanded leaf)

**Comment by Danielcalza** [comment]
Thank you both for the quick response! I just edited and reposted the suggested corrections. 
Please feel free to double check and make any other recommendations.

**Comment by Danielcalza** [comment]
The Agroecosystems Methods have been updated.
