### ISSUE TITLE
Bulk Density protocol update

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/agroecosystems#27]
- Samples taken after mowing
	- Steel ring  2-3"x2-3" placed on soil 
        - wood board placed on top of ring
        - rubber hammer used to tap ring flush into ground
       - cover ring with a cap (to prevent soil from acidentally getting in) 
       - use hand trowel used to get under steel ring and remove sample 
       - placed soil sample into metal 236.6ml (8oz) canister. 
	- Samples weighed and recorded without lid, canister teared 
	- Samples placed in drying oven for 48-96hrs. at 105 C. 
	- Samples weighed and recorded without lid after drying, canister teared  
        - All samples sieved at 2 mm
        - Small aggregates and gravels ground with pestle and mortar 
       - Samples sieved again
       - Separate soil from gravel, weigh and record each 
       - Discard soil, keep gravel 
       - Measure 200ml of DI water
      - Add dried gravel
      - Record water displacement

**Comment by Danielcalza** [comment]
Hi everyone, I wanted to make sure this protocol was through and up to date.
Please feel free to make any corrections or suggestions.

**Comment by Thioro18** [comment]
Great summary Daniel!

**Comment by Danielcalza** [comment]
The Agroecosystems Methods have been updated.
