### ISSUE TITLE
Biomass harvest protocol update

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/agroecosystems#29]
- Biomass harvest and plant count
<ol><li>Label twentyfour (24) brown paper sample bags accordinly</li>
<li> Place 1-meter quadrat in a subplot (9 m2 unit)</li>
<li> Pull out cover crops and weeds by hand</li>
<li> Separate cover crops by species and weeds (not by species)</li>
<li> Count the number of cover crop plants only, for each species </li>
<li> Separate roots from leaves+stems for each cover crop species</li>
<li> Weight roots, leaves+stems for each species. Weigh weeds fresh biomass</li>
<li> Take samples of 200 to 500 g of root and leave+stem biomass for each cover crop species until a total of three (03) samples per species plant part is obtained per two rows (combine rows 1 &2, 3&4, 5&6 as needed)</li>
<li> Take one (01) sample of 200 to 500 g of weeds biomass per row, for total of six (06) for entire plot. 
<li> Place cover crop and weed biomass samples into brown paper bags, keeping stem+leaves seperate from roots and weeds.</li>
<li> Spread remaining biomass evenly over sampled area</li>
<li> Repeat steps 1-11 for each row, for a total of twentyfour (24) samples for the enite plot</li>
<li> Use hedge trimmer to cut and the remaining biomass in the plot</li>
<li> Dry down biomass measurements for 48 hours at 60C and weigh dry biomass</li></ol>

**Comment by Danielcalza** [comment]
Hi everyone, I wanted to confirm these methods. I am a little confused about different references and how many samples we are exactly taking. 

_I wanted to clarify some of the names: "unit" -the entire site?  "plot" - the entire site? "subplot" - a unit inside plot._ 

7. Take a subsample of 200 to 500 g of root and leave+stem biomass for each cover crop species until a total of 03 samples per species plant part is obtained per plot (e.g. AG or SP plot)

_- So from each quadrant measurement, we will have 01 samples from 01 cover crop(e.g Sunn hemp) of its 03 plant parts(root,stem,leaves)_ 
_- So that once we move the quadrant 03 times(within the entire unit), we will have 03 samples from all 03 CC species of their 03 plant parts respectively - so 09 subsamples total?_

**Comment by Thioro18** [comment]
> Hi everyone, I wanted to confirm these methods. I am a little confused about different references and how many samples we are exactly taking.
> 
> _I wanted to clarify some of the names: "unit" -the entire site? "plot" - the entire site? "subplot" - a unit inside plot._
> The plot is the 20m*20m (400 m2) and the subplot is the 3m*3m (9 m2)
> 1. Take a subsample of 200 to 500 g of root and leave+stem biomass for each cover crop species until a total of 03 samples per species plant part is obtained per plot (e.g. AG or SP plot)
> 
The conversion factors from biomass fresh weight to dry weight exist for winter harvest but nit summer. I think it will be useful to take biomass samples for summer as well and see the difference in water contain between the two growing season.
For the biomass sampling, I took 3 replicates for each cover crop. So row 1 and row 2 were for replicate 1, row 3 and 4 were replicate 2, and row 5 and 6 replicate 3. I will explain this to you tomorrow with the plot diagram in front of us. It will be easier to understand that way.

> _- So from each quadrant measurement, we will have 01 samples from 01 cover crop(e.g Sunn hemp) of its 03 plant parts(root,stem,leaves)_
Yes, but if there are 2 species in a quadrat you need to take root and aboveground biomass for each cover crop
> _- So that once we move the quadrant 03 times(within the entire unit), we will have 03 samples from all 03 CC species of their 03 plant parts respectively - so 09 subsamples total?_
Let's us the plot diagram to figure this out. It will be complicated in writing.

**Comment by Thioro18** [comment]
> Thank you both for the input. I have updated the Agroecosystems Methods.

Looks great to me!

**Comment by Danielcalza** [comment]
Thank you both for the input. I have updated the Agroecosystems Methods.
