### ISSUE TITLE
Sunn hemp photos and biomass harvest

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#36]
Hey Daniel, 

Thioro, Ariel and I are finishing up the final bits on the EDIS doc we are writing. Thioro mentioned that there may be good photos of sunn hemp in the shared folder. Do you mind looking and sending me what you find might be helpful for someone seeking to learn more about the crop? We go over several topics including benefits, growth habit, management etc. So anything along the lines of management and use of sunn hemp would be great.

Also, ECHO had to close unexpectedly for human resource reasons (lost a specific insurance coverage that took a bit to get back), so today is my first day back since last Wednesday! I am collecting final heights and CHL in both plots today and am hoping to finish up the biomass for the AG plot tomorrow and the SP plot Friday, but I may have to push the SP plot to Tuesday next week if we get too interrupted by rain. I just wanted you to know I'm harvesting, but it might get a little delayed in the SP plot :/ I hope your harvesting is going well!

Stacy

**Comment by Danielcalza** [comment]
Hi Stacy, 

Glad to hear you all are back up and running! We started to harvest yesterday also, and all is going well. 

I'll look through the photos and them over today. We should have a few good ones of the stands and roots with nodules. 

Best, 
Daniel

**Comment by Danielcalza** [comment]
![SH_flowers](https://user-images.githubusercontent.com/39013993/61064759-608eb100-a3d0-11e9-858a-700944b0e937.jpg)
![SH_roots](https://user-images.githubusercontent.com/39013993/61064760-608eb100-a3d0-11e9-9fb4-133939c25c79.JPG)
![SH_SS_roots](https://user-images.githubusercontent.com/39013993/61064761-608eb100-a3d0-11e9-8507-4f6984db81f0.jpg)
![HH_stand](https://user-images.githubusercontent.com/39013993/61064771-65536500-a3d0-11e9-8fbc-626376329e0d.JPG)

_
Let me know if these are good and if you'll need any more.

**Comment by readersm** [comment]
looks great! Thanks Daniel!

We got rained out most of yesterday and the weeds are taking a long time to gather, so we only finished one row all of yesterday!! Hopefully today is a little smoother...
