### ISSUE TITLE
A few questions from summer 2019

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#37]
I hope you guys are doing well! I am excited that the fall semester is coming up soon and we can catch up at a lab meeting. Lots of data was collected this summer! Harvest took us 3 times as long as normal, but we DID get it done! 

I just uploaded the biomass data collection csv. for this summer's biomass. I still need to finish getting the dry weights for the bulk density samples, but will upload those as well when I finish collecting them. I do have two questions though:

I was wondering, for this season's dry biomass conversion, should I still be averaging that with the past data from last season into the same moisture-content.csv that is already in the folder, or are we wanting to keep those separate based on season or year?

Should I send soil sub-samples down to TREC again from the pre-plant and post-harvest soil samplings for analysis? Or are we going to look at sending them out somewhere else? The post-harvest samples are very much still drying down, so no rush on this. 

Thanks guys!

**Comment by Danielcalza** [comment]
Hi Stacy, all is well here and I hope the same for you and yours! We have been gathering so much data too, and harvest also took up almost 3 weeks between weather and time. But we got it done as well! I am working on organizing and cleaning the data and have uploaded most of it too.  

I'm not sure about the biomass content nor the soil samples.

**Comment by brymz** [comment]
> biomass conversion, should I still be averaging that with the past data from last season into the same moisture-content.csv

You can put it in the same file, but we’ll want to add a column for ‘yield’. The conversion to dry mass for each year will help us with comparing results among year.

> Should I send soil sub- samples down to TREC

Yes, I think. @Danielcalza, are you prepared to be processing the soil samples?

**Comment by Danielcalza** [comment]
Absolutely!  Send them our way, and let me know what we'll be testing for.

**Comment by Danielcalza** [comment]
Hi @readersm, just following up on the email. I'm all set to process your samples for bulk density and organic matter. Let me know if there is anything you need from me to assist you.

**Comment by Danielcalza** [comment]
I was also curious about when you pulled your samples, and if they lined up with my sampling time. I took the ones here at TREC in early May before planting.

**Comment by readersm** [comment]
Awesome! 

I have already processed the bulk density pre-summer. I took bulk densities April 2nd-April 4th! So I was a month ahead of planting (in part because it took a while to prep the fields and I had to take it before tilling). I can process the post-season bulk density as well (I have a moisture meter I use that's pretty easy to process, it just takes a long time).

For OM: Do you want me to wait until the post-season soil samples dry down? We had a really rainy second half of the season, so the samples are really wet (and heavy)!

**Comment by Danielcalza** [comment]
Okay sounds great! Yeah, I hear you, I was also trying to get it done earlier but was stalled by site preparations and waiting for the residues to fully breakdown. 

For the soil samples, you can let them dry for another week or so, but I would like to start working on them by early to mid-Setember the latest if possible. If needed, I can also let them breathe for a week when I open them here. 

And we do have a pH meter now! I just need to calibrate and get familiar with its operations. So we can definitely test your samples as well.

**Comment by readersm** [comment]
Sounds good. How much do you need for each sample to process OM and pH? Thioro had me send down small ziplock bags that each had 5 g each, but I think she was just measuring OM.

**Comment by Danielcalza** [comment]
So those 5 g ziplock bags should be plenty for OM, we only need 0.2-0.5g. But for pH, I'm still looking for the best protocol. If you can please send at least 25 g because most of the procedures I am finding are using 20 g or more.  @Thioro18 Do you know of or have a good pH protocol?

**Comment by Thioro18** [comment]
Hi Daniel,
For pH, I often use a 1:1 ratio (1 m3 soil for 1 m3 of water). I can also be weight to weight ratio. I will send you a detailed procedure when I get home.

**Comment by Danielcalza** [comment]
Okay, please do. In this case, is there a minimum for weight, or could I use the remaining 4 g, of the 5g samples, Stacy sends us? ( 1 g will be used for the OM).  It would be 4 g of soil and 4 g of DI water?
Thank you, 
Daniel

**Comment by Thioro18** [comment]
Daniel, 
I use the Virginia Tech lab procedure for pH (page 4). I will send you the pdf via email. At least 10 cm3 of soil. Now, soil particle sizes are different so you can use a 10 cm3 spoon and weight the corresponding mass of your soil.
You can use plastic tubes and shake the samples as an alternative to stirring. Dr. Li's lab has a shaker.

**Comment by Danielcalza** [comment]
Thank you again, Thioro.  So 10 cm3 is roughly ~10 g. In which case we would need 12 -15 g of soil from you Stacy to make sure there is extra for OM. I'm not sure if the small 5 g bags would be good then.

**Comment by Danielcalza** [comment]
Hi Stacy hope all is well! Just following up on how the samples are drying and when you'll get them down to us. 
@readersm 
> I will plan on giving you a mixed, sub-sample of 15-20 g from each composite sample. I will find a consistent bag size that they fit in well. I will label each bag with the plot and unit ID as well as pre vs. post season. e.g. SP145pre

**Comment by readersm** [comment]
Sorry for the delay. We got the pre-Summer 2019 season samples packed up, but the post-season samples were still very wet, so I let them dry another week in the AC. I will pack them up Friday and probably send them Monday so that they are likely to arrive in the same work week. Is this still the address I should send them to? 18905 SW 280th Street, Homestead, FL 33031

**Comment by Danielcalza** [comment]
Okay sounds great, looking forward to running the analysis. And yes, that is the correct address. If you could please put ATTN: Agroecology

**Comment by readersm** [comment]
The soil samples are in the mail and on their way to you now! Each plot is bagged together based on plot ID. Let me know if you have any questions when you get the package
