### ISSUE TITLE
Planning and preparation of cover crops [September-January]

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/agroecosystems#38]
September
.
9/2 - Set up envelopes and weigh seeds
9/3 - Collect weather station data
9/9 - Print all data sheets and set up Biomass sample bags 
9/16 - Set up Soil Organic Matter sampling bags, organize Bulk Density containers 
9/23 - Communicate with field crew for mowing, plowing, disking
9/27 - Frist mowing of all four sites
.
October
.
10/09 - Collect weather station data
10/10 - Second mowing for OC and HH
10/15 - Plowing all sites
10/21 - Disking all sites
10/28 - Second disking of OC and HH 
10/28 - BD sampling VF
10/30 - BD sampling HH
10/31 - SOM sampling all four sites 
.
November
. 
11/4 - 7 - Set up flags and rake 
11/6 - 8 - Planting (6-VF, 7-FO, 8-HH, OC). 
11/12 - Reinstall soil moisture probes 
11/12 - Collect weather station data
11/13 - Week 1 emergence 
11/20 - Week 2 emergence 
.
December
.
12/2 - Collect weather station data
12/4 - Week 4 Height & Chlorophyll
12/18 - Week 6 Height & Chlorophyll / Canopy?
.
January
.
1/1 - Week 8 Height & Chlorophyll / Canopy?
1/6 - Collect weather station data
1/6 - Harvest

**Comment by readersm** [comment]
Nope, don't worry about it. I can make them here. Thanks for offering though! 

I will need seed again, and would greatly appreciate them parceled out again. I know the AG plot will be the same, but I'm meeting with a committee member next week which might mix up what we are planting in the SP plot. So if we could hold off on sending those for a least a week or two, that would be great!

**Comment by Danielcalza** [comment]
Okay sounds great!

I have already sorted the mucuna seeds, but we're waiting for the other seeds to come in. Let me know when you have decided how you'll prepare the SP plot.

**Comment by Danielcalza** [comment]
> I will need seed again, and would greatly appreciate them parceled out again. I know the AG plot will be the same, but I'm meeting with a committee member next week which might mix up what we are planting in the SP plot. So if we could hold off on sending those for a least a week or two, that would be great!

Hi Stacy!

Just following up if you decided what is needed from the SP plot.  I know with the storm coming it shifted everything around.

**Comment by readersm** [comment]
Yep it did! But I did still get to meet with Dr. Jango. 
AG plot I will need the full, normal breakdown of units (just like you sent last time).
For SP, I will just need a little bulk seed of each of the 3 lots. Enough to sow 4 solo blocks of each species (with a little to spare) would be great! 

Thanks so much for all of your help Daniel!

**Comment by Danielcalza** [comment]
Okay sounds great. So just to clarify, as an example of a solo block for mucuna it would be 50 seeds per block (about 225 seeds for the 4 blocks) right?

**Comment by readersm** [comment]
yep! that would be great

**Comment by brymz** [comment]
Hey @Danielcalza, Let's get the harvest date on the calendar for the lab (and field crew?).

**Comment by Danielcalza** [comment]
> Hey @Danielcalza, Let's get the harvest date on the calendar for the lab (and field crew?).

Done sent out an email. 

I'm planning for the second week of January 1/6/2020.

How does that line up with you @readersm

**Comment by readersm** [comment]
60 days for me lands me at harvesting the third week of January 1/13/2019
So that's what I have on my calendar

**Comment by Danielcalza** [comment]
1.21.2020
- Weather station data collected. 
- Soil probes removed. 
- All Macuna pulled out by roots.
- All sites terminated.
