### ISSUE TITLE
Thoughts on Mucuna and interspecific compeition

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#45]
While writing my proposal, I included the hypothesis that mucuna may have greater interspecific competition as a vining crop, than sunn hemp or sorghum sudangrass. 

> We also anticipate mixtures with mucuna, the only vining crop, to experience the greatest amount of interspecific competition. 

Daniel, do you have thoughts on this? What have you observed in the field? Is there a way we can quantify this?

**Comment by Danielcalza** [comment]
Hi Stacy, yes I have seen similar observations. The mucuna climbs and topples both the sun hemp and sorghum sudangrass. I think the best way of quantifying this is with the LER of biomass for both species, which could show as mucuna vines, it limits the other plants' growth. 

The LER for my poster, of last year's data, suggested that SH and SS have less interspecific competition and produce more biomass in mixture than monoculture while VB may produce more biomass in monoculture showing less intraspecific competition. 

I hope this helps!

**Comment by readersm** [comment]
It makes sense to me physiologically, but I am curious how we can quantify it. I'll try to read up in literature to see if there are ways. Zack and I talked a little about it yesterday. If you have any ideas or run into anything, please send it my way. I'll continue to mull it over.

**Comment by brymz** [comment]
I would suggest that you break out the species components (i.e., Mix1/Mono1) of LER and look at those. The questions would be how each species is contributing to the overall LER.
