### ISSUE TITLE
Set up soil sampling protocol

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/agroecosystems#5]

**Comment by Thioro18** [comment]
**Sampling Periods:**
- Before planting
- Three months after planting
- Six months after planting
**Sampling tools:** 
- Auger or probe
- 03 composite-sample per plot 
- Ziploc bags Quart (36*4*3= 432 bags for TREC and 36*2*3 = 216 for ECHO)

**Comment by Thioro18** [comment]
I close this by mistake

**Comment by Thioro18** [comment]
**Sampling Periods:**
- Before planting
- Three months after planting
- Six months after planting

**Sampling tools:** 
- Auger or probe
- 03 composite-sample per plot 
- Ziploc bags Quart (432 bags for TREC and 216 bags for ECHO)

**Comment by brymz** [comment]
Looks like a good start! Are you looking for any specific feedback, yet?

**Comment by Thioro18** [comment]
Yes, if you have suggestions, please add them. I put the list here so that I can update the soil methods as we go through the CC trial.

**Comment by Thioro18** [comment]
[CC Experimental Design.docx](https://github.com/TREC-Agroecology/agroecosystems/files/1872354/CC.Experimental.Design.docx)

**Comment by brymz** [comment]
Ok. I put this document in `Agronomy/CropDiversity/CoverCrops/AgroecosystemsExperiment/`.

> How do you get to 432 samples for TREC?

I think what I was getting at is: 36 subplots \* 4 plots \* 3 sampling periods = 432 samples
Is that right?

**Comment by readersm** [comment]
Looks like a great start! Thanks Thioro! 

We get OM boosts quickly with our soil types at ECHO with GMCCs. I would be really interested to know the difference in OM changes over time between the two plots here, even if we test for them more infrequently. I don't know how the analysis process works though or how difficult it is, so I will leave that up to your insight and knowledge Thioro.

Should we get a baseline texture analysis on each soil type?

Lastly, the lab we send samples to always tells us to put the samples in paper bags, not plastic. I don't know why though. Thioro you probably do. I just wanted to bring it up in case any of the nutrients are impacted by storage in plastic over time or freezing. I know Nitrate values fluctuate if I don't get samples out of the sun right away or freeze the samples shortly after taking them if I plan to send them at a later date.

**Comment by brymz** [comment]
@Thioro18, please add the details of the sampling protocol to https://github.com/TREC-Agroecology/agroecosystems/wiki/Agroecosystems-Methods#soil-sampling

**Comment by Danielcalza** [comment]
The Agroecosystems Methods have been updated.
