### ISSUE TITLE
Sunn hemp flowering in winter

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/agroecosystems#50]
Hi Stacy! @readersm 
So we most likely planted a different variety than Tropic Sun this winter. 
I was curious if you have any notes on the sunn hemp and if it flowered early from last winter?

**Comment by readersm** [comment]
Hey Daniel! 
It didn't reach ~50% flowering until ~60 days after planting last winter which is normal. It looks like it's going to flower much earlier this winter though! Here are photos from last year
Earliest budding I noticed started on Jan 3rd
![Jan 3 2018](https://user-images.githubusercontent.com/36899811/71194243-97a79f00-2259-11ea-919d-a7e7aad9d466.JPG)
I'd say we were at ~60% flowering at harvest (Jan 22nd)
![Jan 22 2018](https://user-images.githubusercontent.com/36899811/71194280-a5f5bb00-2259-11ea-9e5d-b6f7e09ad6b7.JPG)

**Comment by Danielcalza** [comment]
Thanks Stacy! I'll add this to my notes.
