### ISSUE TITLE
Data files?

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#53]
Hey Zack,

I just did a quick analyzes of the BD data from summer 2019 at ECHO. I am mostly playing around with the easy stuff I know how to do right away (paired T test,  anovas, made some box plots to look at the data). Should I push that up as well or just keep that for myself? I did annotate it a little

Sadly, the BD went **up** from pre to post season here (significantly different between time)! Though still within normal ranges for sandy soils. No CropTrt significance though and no Time:CropTrt interaction.
![BD boxplots](https://user-images.githubusercontent.com/36899811/71286081-bcbd1000-2334-11ea-9295-4728469009e6.jpeg)

**Comment by brymz** [comment]
It's more important to push the code that gets to the results. I can then run that code to generate the results.

**Comment by readersm** [comment]
Ok, I'm going to add one or two more tests and then upload it
