### ISSUE TITLE
Planning and preparation of Agroecosystems Experiment [March-July]

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/agroecosystems#55]
March
.
3/2 - Set up envelopes and weigh seeds for both TREC and ECHO
3/9 - Print all data sheets and set up Dry Down Biomass sample bags
3/11 - Set up Soil Organic Matter sampling bags, organize Bulk Density containers
3/16 - Communicate with field crew for mowing, plowing, disking, and irrigation 
3/16 - Frist mowing of all four sites
3/18 - Collect weather station data
.
April
.
4/6 - Second mowing for OC and HH as needed
4/6 - Plowing all sites
4/17 - Collect weather station data
4/20 - Disking all sites
4/22 - BD sampling VF
4/23 - BD sampling HH
4/27 - Second disking of all sites as needed
4/28-29 - SOM sampling all four sites
.
May
.
5/4-6 - Rake rows and set up flags
5/6-8 - Planting (6-VF, 7-FO, 8-HH, OC).
5/11 - Reinstall soil moisture probes
5/11 - Collect weather station data
5/20 - Week 2 Emergence
.
June
.
6/3 - Week 4 Height & Chlorophyll
6/17 - Week 6 Height & Chlorophyll
6/18 - Collect weather station data
6/24 - Week 6 Height & Chlorophyll / Canopy?
.
July
.
7/1 - Week 8 Height & Chlorophyll / Canopy?
7/6 – Harvest
7/13 - Collect weather station data
7/13 - Remove soil moisture probes 
7/20 - Terminate all sites

**Comment by Danielcalza** [comment]
@readersm Hi Stacy, 
Checking in on your seed needs for summer planting, are you doing the same as last winter again?

Here is what you had asked for: 
AG plot - the full, normal breakdown of units (just like last time).
SP - just a little bulk seed of each of the 3 lots. Enough to sow 4 solo blocks of each species (with a little to spare), and to clarify - as an example of a solo block for mucuna it would be 50 seeds per block (about 225 seeds for the 4 blocks).

**Comment by readersm** [comment]
Hey Daniel,
**Yes** - I need the same as last winter. Thanks so much for checking! If you could give me just a little extra of the bulk to spare, that would be great. I'd like to fit in two more reps, but I don't know if it will happen. I have some spare bulk from last summer, but I think you got a new sorghum lot, correct?

**Comment by Danielcalza** [comment]
@readersm Hey Stacy, 
Great. I'll be putting these all together this week and have them out to you. 
For the sorghum, yes we did get a new lot - would like the older one (not coated) or the new one?
