### ISSUE TITLE
Soil sampling SOP

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/agroecosystems#56]
Hi @readersm !

I wanted to confirm your methods so we could sync our SOP. Are you taking soil samples before each planting and then immediately after harvest as well? I had meant to ask when sent the samples before and they were labeled pre and post. 

I have been taking them before each planting, after terminating and incorporation.

**Comment by readersm** [comment]
Yep! Before each planting and then right after harvest (after I cut them all at the base). I haven't taken any after incorporation. I let the residues break down on the soil surface and don't till until the next season.

**Comment by Danielcalza** [comment]
Okay thank you and sounds great! After speaking with Zack we are going to continue taking samples once before each planting.
