### ISSUE TITLE
ECHO plot set up

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#6]
We've been busy clearing and discing and have made a lot of progress.
Here's what it looks like now in South Growout
![img_9765](https://user-images.githubusercontent.com/36899811/38440629-05209cc4-39b0-11e8-86ca-8e8a911c8009.JPG)
And in the scrub
![img_9789](https://user-images.githubusercontent.com/36899811/38440687-3474458e-39b0-11e8-8bd3-344c12d9af5f.jpg)

We got all but one large stump out, so a guy is going to come and grind it out next week. Tim Watkins asked if we need to square the plot north-south like we normally do.  I didn't have an answer for him. Is it important we have it squared in dimensions and direction?

I'll be discing south growout one more time then setting up the irrigation. After the stump is out, I'll rake and set up irrigation out in the scrub. I'm looking forward to the diversity survey! Let me know if there is anything I can do to help. Our Farm Manager Assistant is also very excited. He found [false pawpaw](http://florida.plantatlas.usf.edu/Plant.aspx?id=1090) out near our primary site last week.

**Comment by brymz** [comment]
> Tim Watkins asked if we need to square the plot north-south like we normally do. I didn't have an
> answer for him. Is it important we have it squared in dimensions and direction?

Yes, sort of. We will have the plots squared to TREC, which is not exactly N-S. I recommend doing what is a reasonable effort in the given priorities: 1) square the plot to itself, so sub-plots are square, 2) square the plots to each other, 3) square the plots N-S as the plant diversity survey is squared N-S. At TREC we only make it to priority 2.

**Comment by Thioro18** [comment]
![cc-expdesign](https://user-images.githubusercontent.com/31212467/38752203-6b0c31ba-3f28-11e8-96d9-13d6b60a5e96.jpg)
![pds-expdesign](https://user-images.githubusercontent.com/31212467/38752207-6d9e16b4-3f28-11e8-9022-af5f6f53be93.jpg)
[Arrangement.docx](https://github.com/TREC-Agroecology/agroecosystems/files/1908533/Arrangement.docx)

**Comment by readersm** [comment]
Sounds great! I will probably be able to accomplish 2, but not 3 as well on the squaring of the plots. I will be putting in painted posts that when strings are pulled between interior edges of the posts, mark the plot. This is mostly so that are tractor can get the whole interior of the plot when prepping for future seasons.

I'm ordering final parts for the irrigation on Thursday and will have them built by the time Thioro and Cliff arrive here.

**Comment by readersm** [comment]
I just realized that Thioro and Cliff, you will be coming on a week that we have a course! This could be great or horrible... our housing might be full - but I will wait to hear back from the hospitality manager. Also, I have to teach from 6:30-10am Thursday May 3rd, but hopefully David (our staff member who enjoys plant ID) could help with the PDS in that time. It's also our hurricane preparedness week - but they will most likely switch that because of the course. I will keep you in the loop

**Comment by brymz** [comment]
We did it! Well done, team.
