### ISSUE TITLE
Data Organization

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#60]
- [x] Make unique table for weed data (stacked over seasons)
- [x] Add season column to BD and harvest tables or do we just want to bind tables on unique identifier and use year? (decide with Daniel)
- [x] Update moisture content file from winter 2019 data
- [x] Add Harvest 012020
- [x] Review README.md with Daniel and make file names consistent with

**Comment by readersm** [comment]
@Danielcalza I have the moisture content from last season (Winter 2019). I remember for some reason, adding it to the raw last summer into the moisture-content.csv file, but that file just has averages for above and belowground biomass conversions. Do you know where I should put the dry down data for last season?

**Comment by Danielcalza** [comment]
Hm I'm not sure. This is the moisture content of the fresh biomass from harvest right? I think it should be its own file.

**Comment by readersm** [comment]
Yeah, from the drying down of the sub-samples for rows 1&2, 3&4, and 5&6. We used to have a file for all of the moisture values across seasons, but I don't see it anymore.

Also, I just sent the soil samples from winter 2019 AG plot (pre and post separated) the tracking number is 9114902307224713401813

**Comment by Danielcalza** [comment]
I'm looking through the shared drive and can't seem to find one. Is there a chance you have it stored locally somewhere? I'll also try to see if it was accidentally removed but I'd like to think that Git would have shown and made us aware of the changes. 
I have the data stored with the fresh weights in the Dry_Biomass file. 

And sounds great for the samples, I'll be looking for them.
