### ISSUE TITLE
Tidying Data

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/agroecosystems#61]
- Found harvest biomass sheet had blanks from the multiple species for the weeds biomass. 
- Moved the weeds data into a separate table so no blanks would occur.
- Reviewed README for consistency in column naming. 
- Making edits to README. Found repeats and difference between TREC and ECHO
- Communicating with @readersm to solidify consistency

**Comment by Danielcalza** [comment]
Hi @readersm I wanted to ask how are you noting `missing data`? Are you leaving it blank or recording NA. I've gone through most of my files and have them recorded as blanks. I'd like to add this to the README as well.

**Comment by readersm** [comment]
I'm recording NA for mine... haha
I know how to work in R with NAs, I'm not sure how to work with blanks, but I can ask Zack to teach me today and then can change them

**Comment by Danielcalza** [comment]
Hahh! No it's fine, all is well. I have some NAs too. If the workflow is better in R with NAs, I'd vote to go with that.

**Comment by readersm** [comment]
We can ask Zack today. He has been writing most of the analysis, and then go forward from there. I just realized today that I still have SiteName instead of Location, so I will fix those today at some point.
