### ISSUE TITLE
Sending soil subsamples?

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#64]
Hey @Danielcalza the post-harvest soil samples have dried down fairly well. Do you want me to send down sub-samples yet like I did last season? I can also wait to send them, just wanting to make sure I stay on top of things before next season. 

Also, was the volume of sample enough last time for all analysis? I sent ~20 g per sample. 

Stacy

**Comment by Danielcalza** [comment]
Hey Stacy, yes please send them down if the samples are dry enough. The sooner the better. Larousse will be helping us too, so hopefully it goes a little faster. 

As for the amount, if you can send ~60g, I think that would be enough. I was figuring out the best methods for pH and found that using ~40g for the TREC samples was a reasonable volume. Although, I still was able to get precise readings on less when I tested the ECHO samples, but I'd like to have a little extra just in case.

Let me know if you need me to send anything, sampling bags..etc.

**Comment by readersm** [comment]
No problem, I can send 60g. I think the bags I have will fit 60g. 

I'll prep and send them next week.
