### ISSUE TITLE
Litter Bag ordering

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#70]
@Danielcalza Zack and I have figured out what supplies will be needed for the litterbag trial this upcoming season at ECHO. 

Could you please order for me, the 200-count Fiber Filter Bags from Ankom technology on [this website](https://www.ankom.com/product-catalog/fiber-filter-bags
) (SKU: F57) and have the package sent to ECHO? Below is the address for ECHO. I will make sure to scan and send back the packing slip when I receive the package.
ECHO Attn: Research Department
17391 Durrance Road
North Fort Myers, FL 33917

**Comment by Danielcalza** [comment]
Okay sounds great. I am trying to place the order now but having some issues with the site. I am in contact with the sales team and will report once the order is confirmed. 

Aside: the seeds should be on there way by today or tomorrow.

**Comment by Danielcalza** [comment]
I ended up calling in the order and it should be shipping out tomorrow.

**Comment by readersm** [comment]
Thanks so much!!
