### ISSUE TITLE
Cover crops litter decomposition 

### ISSUE THREAD

**Issue by Larousse24** [TREC-Agroecology/agroecosystems#74]
•	Collect six 200g samples of fresh aboveground biomass for each cover crop species (sunn hemp and sorghum sundangrass).
•	Dry them down in a forced-air drier at 75 degrees C to a constant weight (no change for two consecutive samples 24 hours apart).
•	Four 50 g dried biomass samples per species will be sent for analysis of N and C.
•	Collect a random amount of fresh aboveground biomass for both species 
•	Cut and weight them based on the appropriate ratio (0-100, 25-75, 50-50, 75-25, 100-0).
•	Each treatment will have four replicates and 6 retrieval dates which will give 120 litterbags in total.
•	Each litterbag (0.02 m2) will have 25g of fresh-cut aboveground biomass, which will be 20 bags per ratio.  
	100SH/0SS (25g of sunn hemp)
	75SH/25SS (18.7g of sunn hemp and 6.3g of sorghum)
        50SH/50SS (12.5g of sunn hemp and 12.5g of sorghum)
        25SH/75SS (18.7g of sorghum and 6.3g of sunn hemp)
	0SH/100SS (25g of sorghum)
•	Heat-seal the bags and then place them  randomly back in the field from where the cover crop biomass was harvested.
•	Pin them to the soil surface with ground staples. 
•	Flag to make sure the position is clear.
•	Retrieve the litterbags at 4, 7, 14, 28, 42 and 56 days after placement from soil surface.
•	Send the samples to Dr. Ruzi Moreno’s lab in North Florida Research and Education Center, for analysis of N and C. 
•	Ash analysis will be performed at TREC using a Muffle Furnace.

**Comment by readersm** [comment]
Great summary Larousse! You will want to heat-seal before you randomly place them for ease of placement. 

Also, make sure that when you put the biomass into the litterbags, it is representative of the whole plant. I doubt one whole plant will go into each bag (it is likely less), so make sure to use representative amounts from the whole plant. You may have to take subsamples from the top, middle, and base sections of the plant to make up what sample tissue goes into the litterbag. Let me know if you have questions about that! I will be harvesting biomass and prepping litterbags next week!

**Comment by brymz** [comment]
Hi @Larousse24! This looks great. Could you please move this over to a [new wiki page](https://github.com/TREC-Agroecology/agroecosystems/wiki/_new)

**Comment by brymz** [comment]
You may add in the details that this was done at TREC (~7/6/2020) in Block 1.

**Comment by Larousse24** [comment]
@brymz , I think I am not permitted to add a new wiki page cause they don't give me that option.

**Comment by Larousse24** [comment]
Thank you @readersm for providing some feedbacks. I will be harvesting biomass and prepping litterbags in two weeks!

**Comment by brymz** [comment]
@Larousse24, You should have an email that invites you to the TREC-lab team that will give you access to edit the wiki.

**Comment by Danielcalza** [comment]
Moved to the [wiki] (https://github.com/TREC-Agroecology/agroecosystems/wiki)
