### ISSUE TITLE
New visualization for LER fraction (can talk about tomorrow)

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#75]
I was able to map the first LER species fraction with error bars (see below), but I can't figure out how to add a second bar, same color, next to it and get them labeled separately on the x axis. What I try keeps combining the 3 occurrences of each species into one bar (that then has 3 error bars).
![LER fraction](https://user-images.githubusercontent.com/36899811/85449362-abfc8980-b565-11ea-929c-32b98e496fe0.png)

Here are the lines of code I'm working from to get the above visualization 
ggplot(LER_row_summary, aes(x=spp, y=mean_LERfract_sp1)) +
  geom_bar(stat="identity", aes(fill=spp)) +
  geom_errorbar(aes(ymin=mean_LERfract_sp1-ci_LERfract_sp1, ymax=mean_LERfract_sp1+ci_LERfract_sp1), width=0.2) +
  facet_grid(.~j) +
  geom_hline(yintercept = 0.5, linetype="dashed") +
  scale_fill_manual(values=c("#AF601A", "#8E44AD", "#196F3D")) +
  labs(x="Crop Mix", y="LERfraction [+/- 95% CI]") +
  theme_bw(base_size = 24, base_family = "Helvetica") +
  theme(axis.text.x = element_text(size=14, angle=30),
        legend.position = "none")

Also! Exciting news about the T-tests, if I did them correctly. I did them first with the full data of LER calculations by row, then just using the means from the row_summary table:

# Whole dataset (each row's value for LER per Croptrt)
**One Sample t-test: SH-SS LER**
t = 5.1166, df = 107, p-value = 6.888e-07
alternative hypothesis: true mean is greater than 1
95 percent confidence interval:
 1.278057      Inf
sample estimates:
mean of x 
   1.4115 

**One Sample t-test: SH-VB**
t = 6.9669, df = 107, p-value = 1.375e-10
alternative hypothesis: true mean is greater than 1
95 percent confidence interval:
 1.286623      Inf
sample estimates:
mean of x 
 1.376222 

**One Sample t-test: SS-VB**
t = 7.1877, df = 107, p-value = 4.652e-11
alternative hypothesis: true mean is greater than 1
95 percent confidence interval:
 1.260189      Inf
sample estimates:
mean of x 
 1.338278 

# Calculating t-value with summary data (means per Croptrt over seasons)

**One Sample t-test: SH-SS**
t = 2.5632, df = 2, p-value = 0.06221
alternative hypothesis: true mean is greater than 1
95 percent confidence interval:
 0.9427223       Inf
sample estimates:
mean of x 
   1.4115 

**One Sample t-test: SH-VB**
t = 3.2935, df = 2, p-value = 0.04056
alternative hypothesis: true mean is greater than 1
95 percent confidence interval:
 1.042666      Inf
sample estimates:
mean of x 
 1.376222 

**One Sample t-test:SS-VB**
t = 4.4105, df = 2, p-value = 0.02388
alternative hypothesis: true mean is greater than 1
95 percent confidence interval:
 1.114322      Inf
sample estimates:
mean of x 
 1.338278

**Comment by brymz** [comment]
We'll start by looking at your table structure. Sometimes the table needs to change to make it work in `ggplot()`

> ggplot(LER_row_summary, aes(x=spp, y=mean_LERfract_sp1)) +

would look something like `ggplot(LER_row_summary, aes(x=CropTrt, y = mean_LERfract, group = CropSp)`

> facet_grid(.~j) +

would look something like `facet_grid(CropSp~j)`.
