### ISSUE TITLE
Litterbag biomass calculations

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#78]
Hey Zack!

I tried to add my harvestAgonly.R file so I could just ask you to look at the lines, but ran into some problems I couldn't troubleshoot. I tried using git stash, but then I couldn't help it find the file I did want again. Here's a screenshot of my command prompt issue:
![image](https://user-images.githubusercontent.com/36899811/86616634-22e14b80-bf84-11ea-8aea-368404ec4206.png)

But I think I have the correct biomass calculations for stuffing the litter bags with correct ratios per species. I also calculated how many stems (to give myself an estimate). Would you mind looking it over to make sure it's correct before I stuff and place them tomorrow? The litter bags are 0.02 m^2, so there is a factor of 50 in the mutate lines. I have a meeting all afternoon, but will be placing the litterbags first thing tomorrow. 

Also, is it ok that I used the values for all 6 rows of Crop treatments, but am only placing bags in the middle 4 rows? Should I instead only average the data from rows 2-5 where the litterbags will be placed?

### calculating how much mass (g per species) and how many stems go into each litterbag treatment
biomass_s2020<-read_csv("data/harvest-072020-ECHO.csv")

biomass_data_s2020 <- biomass_s2020 %>%
  mutate(SiteName = str_sub(str_extract(biomass_s2020$PlotName, ".._"), end=2),
         CropTrt = str_sub(str_extract(biomass_s2020$PlotName, "_.*-"), 2,-2),
         LeavesStems_litterbag = LeavesStems_g_1m2/50,
         Stem_litterbag = StemCounts/50) %>% 
  filter(CropSp == 'SS' | CropSp == 'SH' | CropSp == 'VB', SiteName== 'AG') %>%
  group_by(CropTrt, CropSp) %>%
  summarize(avg_g_LeavesStems_litterbag = mean(LeavesStems_litterbag),
            avg_StemCount_litterbag = mean(Stem_litterbag))
### resulting table

CropTrt | Species | avg_g_LeavesStems_litterbag | avg_StemCount_litterbag
-- | -- | -- | --
SH | SH | 6.382222 | 0.4144444
SHSS | SH | 2.534444 | 0.2111111
SHSS | SS | 12.254444 | 0.6522222
SHVB | SH | 4.063333 | 0.2233333
SHVB | VB | 1.161111 | 0.0577778
SS | SS | 14.574444 | 1.2277778
SSVB | SS | 13.155556 | 0.7166667
SSVB | VB | 1.176667 | 0.0544444
VB | VB | 3.222222 | 0.0922222

**Comment by brymz** [comment]
Hi Stacy,

The code problem is extra `''`. It should be `git add harvestAgonly.R`

Code seems like it would provide accurate output. Looks like you got a LOT of SS this year. Is that comparable with previous summers?

Hope bag laying went smoothly!

**Comment by readersm** [comment]
The Sorghum grew really well with all of the heat we have had this summer! I think it is comparable with previous summers, if not more. The sunn hemp seemed much less abundant, and yellowed. This may be perhaps because of the lack of rain we have had so far. 

Do you think using biomass values for all 6 rows of Crop treatments the way I did is OK, even if I am only putting them in 4 of the rows (2-5)?

I actually didn't place them today. I am 100% ready to go, but woke up with a sore throat so I had to go get a COVID-19 test. ECHO's policy is that I can't come back in until I get a negative result or quarantine for an appropriate amount of time (if it's positive). I asked if I can have an exception for only field work (I don't go into buildings) so that I could still do the litterbag placement. I don't know what they will say though. How long do you think would be too long past the harvest date to stuff and lay the litterbags? I left plants still growing so that I take same-day fresh weights, but the plants may change in woodiness or other features before too long... I'm worried I may not be able to get them down in time.

**Comment by brymz** [comment]
You calculation of all 6 rows is ok. Sorry to hear of your sore throat. Health first. Just let me know how things move along and we'll make the best decision.

P.S. I won't be available for our meeting tomorrow. So, let me know if there are other updates to discuss.
