### ISSUE TITLE
Running a 4 loop with 1 species

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#79]
How do I use the console again to run just 1 species in a 4 loop? I've tried everything I can think of to remember how you showed me and have looked on forums, but found nothing helpful. For the total biomass graphs, I can only get VB to go through the 4 loop even though all the tables and previous objects are correct. 

![VBseasonsbiomass](https://user-images.githubusercontent.com/36899811/87469008-93254800-c5e8-11ea-93ee-8c288efeeea0.png)
Also, now looking at just seasons, one of the LERs is significantly greater than 1!
I'm working on binding the fractions and making that graph. I calculated the LERfractions several steps before, so I'm trying to hunt down and figure out how to organize them all into one column and just have the LER total repeat. Or bind them afterwards, which wasn't working for me because it said I didn't have the right number of arguments. 
![summer-winterLER](https://user-images.githubusercontent.com/36899811/87468039-e4343c80-c5e6-11ea-8fb9-7bf2ab2c0f30.png)

Also, I tried uploading the code using the control panel again from this laptop (different computer than before), and it says I don't have permission. Very frustrated at this point.

**Comment by brymz** [comment]
Hey Stacy,

This sort of experience of having to go back and incorporate new data or processes into your code is a major hurdle and one that defines your next developmental milestone with coding. It's a tough one that puts your current knowledge in a generalized and adaptable package, but worth the time to master. Remind yourself that you-in-the-future is *very* likely collaborator.

As far as for loops with one identity, you actually skip the loop, define your object (`i`), and independently run each line of code:

Option 1: `for (i in vector){ do_something_to(i) }` -> `for (i in vector[1]){ do_something_to(i) }`
- `vector[1]` denotes the first item in the vector. You can also just identify an object `"VF"`
Option 2: `for (i in vector){ do_something_to(i) }` -> `i <- "VF"`; `do_something_to(i)`
- once setting `i`, run each line of code in the loop.

**Comment by readersm** [comment]
Thanks!!
I have a couple of items I still need help troubleshooting, but hopefully they will be quick!
