### ISSUE TITLE
Field preparation SOP 

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/agroecosystems#83]
The following questions should be answered once an experiment or research project is in the process of or has already been proposed.
Please be as detailed as possible in the responses, and add any missing or particular information.

Project information:
• Projected Start Date-
• Projected End Date-
• Projected Planting Date-
• Preferred block-	
• Section-
• Area/Acres requested-
• Crop(s)-
• Project Manager-

Land Preparation:
• Describe below the land preparation needs (e.g., mowing, moldboard plow, disc, and level the field, form raised beds, drilling holes, etc.).
•
• Plastic mulch, list below the type of plastic that should be used (e.g., plastic-type: thickness in mls, black on black, black on white, metalized, etc.).
•
Irrigation: 
• Drip Tape, describe below the drip tape layout and specs (e.g., drip placement, emitter spacing, flow-rate GPM/100 ft., etc.).
• 
• Solid set (overhead irrigation).
• 
• Irrigation Schedule, describe below the amounts, frequency, and intervals (e.g., days per week, times per day, min per day, etc.).
•

Applications:
• Fertilizer, describe below the fertilizer, NPK, rate per acre, and application method and frequency (e.g., banded on top of the bed, soil incorporation, etc.).
•	 
• Pesticide, list below the product name, method of application, and rate per acre (e.g., pre-plant broadcast incorporated, shank or drip applied, etc.).
•	 	 
Planting: List below the planting instructions.
• Number of Rows and Length
•
• In Row spacing
•	
• Between Row spacing (buffers)
•	
• Transplants
•	
• Seeding (Direct, Broadcast, Incorporated, Drill, Earthway, etc.)
•
• Rebar and String
•
• Describe Experiment
•		 
• Full diagram of field layout design w/ randomization 
•	
Project Maintenance:
• Harvesting and Grading: The field staff will assist only when available. Submit a work order in advance for the proposed harvesting period.
•	
• Project removal: Inform the farm supervisor when field projects are finished to allow scheduling of the removal process.

**Comment by brymz** [comment]
Hi Daniel,
Can you move this to a wiki page on the `lab-wiki` repo? I can help with some formatting and revision there. Also, let's add a list of things that **must** be complete for project implementation (e.g., UFarm, send SOP form to Jose, etc). There might be a preparation checklist, as well, that includes notes for things like fertilizer purchase or other things that could delay project initiation.
~Zack

**Comment by Danielcalza** [comment]
Okay. I moved it over and added the minor edits. I had put it as an issue first for review and comments.
